### ISSUE TITLE
Required resources and time for training OpenScene

### ISSUE THREAD

**Issue by Solacex** [pengsongyou/openscene#1]
Hello

Thanks for your inspiring work.
Is the current code complete and ready for running? and how long does it generally take with 4/8 x A100s ?

**Comment by pengsongyou** [comment]
Hi @Solacex 

Thanks for the interest in our work. If you directly use our pretrained model for evaluation, it just needs a machine with 20G GPU memory or so. If you wanna distill a model yourself, depending on your dataset, you normally needs 1-2 V100 or A100 to train for 1-2 days (2 A100s were the max I ran). If you have 4-8 A100s, you can increase the batch size, so the training can be faster. 

The code is complete, and you should be able to train on your own.

Best
Songyou

**Comment by Solacex** [comment]
Cool, Thanks for the prompt response.
