### ISSUE TITLE
Feature fusion of nuScenes

### ISSUE THREAD

**Issue by gbliao** [pengsongyou/openscene#10]
Hi.  Thanks for your great work！

How do I implement the feature fusion of nuScenes?  Because I don't find the nuScenes_openseg.py file in the code. 

I would like to ask when the multi-view fused features of nuScenes will be released?

**Comment by chenhaomingbob** [comment]
+1. I have the same question.

**Comment by pengsongyou** [comment]
hi @chenhaomingbob @gbliao,

I have included the OpenSeg multi-view fused features for nuScenes validation sets for downloading using [download_fused_features.sh](https://github.com/pengsongyou/openscene/blob/main/scripts/download_fused_features.sh). Also, I made a mistake before and included wrong 3D lidar point clouds for nuScenes. It is also updated, please re-download it accordingly using [download_dataset.sh](https://github.com/pengsongyou/openscene/blob/main/scripts/download_dataset.sh). 

With them, you should be able to reproduce the results shown in the paper.
