### ISSUE TITLE
train on my own dataset

### ISSUE THREAD

**Issue by gxu12** [pengsongyou/openscene#13]
Hi!
Is it possible to train this project on my own dataset? 
Thank you!

**Comment by pengsongyou** [comment]
Yes sure. You can adapt our [2D/3D processing](https://github.com/pengsongyou/openscene/blob/main/scripts/preprocess/README.md) pipeline and codes accordingly, and adapt the code for [multi-view feature fusion](https://github.com/pengsongyou/openscene/blob/main/scripts/feature_fusion/README.md). Then, you can just distill a 3D model with your own data.
