### ISSUE TITLE
How to get the ".pt" file？

### ISSUE THREAD

**Issue by gbliao** [pengsongyou/openscene#14]
How to get the ".pt" file from nuscenes_multiview_openseg_val? 

However, the files obtained from nuscenes_multiview_openseg_va are "color", "K", and "pose". 

Moreover, what do the above "K" and "pose" files mean? How are they generated?

Can you help me?

**Comment by pengsongyou** [comment]
Please follow [here](https://github.com/pengsongyou/openscene#multi-view-fused-features) to download the features. Remember to download the updated nuscenes 3D point clouds.
