### ISSUE TITLE
Multi-view fusion in nuscenes

### ISSUE THREAD

**Issue by Liuxinyv** [pengsongyou/openscene#15]
Thanks for your excellent wrok! Additionally, I would like to know which images among 'CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_BACK_RIGHT', 'CAM_BACK', 'CAM_BACK_LEFT', and 'CAM_FRONT_LEFT' are used for multi-view fusion in nuscenes.

**Comment by pengsongyou** [comment]
You can check the feature fusion code for nuscenes [here](https://github.com/pengsongyou/openscene/blob/main/scripts/feature_fusion/nuscenes_openseg.py#L40-L71). We used all directions for multi-view feature fusion.
