### ISSUE TITLE
How to obtain ideal test results on the nuscenes dataset?

### ISSUE THREAD

**Issue by Liuxinyv** [pengsongyou/openscene#2]
Hi，thanks for your interesting work！
And I have some questions.
According to your config.yaml, I tested the nuscenes dataset using the nuscenes_openseg.pth.tar checkpoint you provided and obtained an mIoU of only 29, which is not the 42 published in the paper. How can I solve this issue?
![output](https://user-images.githubusercontent.com/58657147/230725279-244c161b-7557-47f8-b75a-d6ebaf627839.png)

**Comment by pengsongyou** [comment]
Hi @Liuxinyv 

Thanks for your interest and trying out our code already! I guess you specify the `feature_type` to be `distill`? You need to have our 2D-3D ensemble model to yield the best performance for nuScenes. However, You can only run `ensemble` when having the 2D multi-view fused features :) We are currently still processing the multi-view fused features for nuScenes, and also preparing the feature fusion code for nuScenes, see our [TO-DO List](https://github.com/pengsongyou/openscene#todo). We will try to release that ASAP, please stay tuned.

Best
Songyou

**Comment by chenhaomingbob** [comment]
@Liuxinyv 
Thanks for your  report! I have a question. Do you meet the `FileNotFoundError`  when you tested the nuscenes dataset?

The details of the error is:
`FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes_multiview_openseg/000681a060c04755a1537cf83b53ba57.pt'`

**Comment by gbliao** [comment]
@pengsongyou Hi. Thanks for your great work！

I would like to ask when the multi-view fused features of nuScenes will be released?

**Comment by gbliao** [comment]
@Liuxinyv @pengsongyou 

Hi. 

Where can I find the nuscenes_openseg.pth.tar checkpoint?

**Comment by pengsongyou** [comment]
Hi @Liuxinyv @chenhaomingbob 

I have included the multi-view fused OpenSeg features for nuScenes validation sets for downloading using [download_fused_features.sh](https://github.com/pengsongyou/openscene/blob/main/scripts/download_fused_features.sh). Also, I made a mistake before and included wrong 3D lidar point clouds for nuScenes. It is also updated, please re-download it accordingly using [download_dataset.sh](https://github.com/pengsongyou/openscene/blob/main/scripts/download_dataset.sh). 

With them, you should be able to reproduce the results shown in the paper.

**Comment by synsin0** [comment]
I have a question of reproducing the result. I train the net with the default config. But the training log and the evaluation doesn't match. In the training log the best val mIoU is 28.7 which is close to 29. In evaluation I test my best checkpoint with distill mode and gets mIoU=41, mAcc=55.8. If I test with official checkpoint, it gets mIoU=42, mAcc=56 in distill mode, which is different from mIoU=29. Why evaluation during training and independent test differs in accuracy?

**Comment by synsin0** [comment]
Are there some differences between the validation and evaluation(test) process for distilled model only?
