### ISSUE TITLE
Openseg feature

### ISSUE THREAD

**Issue by star9988rr** [pengsongyou/openscene#24]
How do you extract Openseg image feature in detail since Openseg predicts masks?
`if regional_pool:
        image_embedding_feat = results['ppixel_ave_feat'][:, :crop_sz[0], :crop_sz[1]]
    else:
        image_embedding_feat = results['image_embedding_feat'][:, :crop_sz[0], :crop_sz[1]]
`
What is the difference between the results['ppixel_ave_feat'] and results['image_embedding_feat']?

**Comment by pengsongyou** [comment]
Hi, 

Thanks for the question. Actually that is something legacy I forgot to change. We always assume `regional_pool` to be True, so only `results['ppixel_ave_feat']` should be used. 

Best
Songyou
