### ISSUE TITLE
demo: OSError: Address already in use

### ISSUE THREAD

**Issue by dbuck** [pengsongyou/openscene#28]
in the demo app, you can run into the Address already in use error message if you manage to crash/exit uncleanly.

Just adding a note that, at least on osx, you can find/kill the process id via netstat rather than edit the port as noted in the https://github.com/pengsongyou/openscene/tree/main/demo#troubleshooting
```
netstat -anvp tcp | awk 'NR<3 || /LISTEN/'

Proto Recv-Q Send-Q  Local Address          Foreign Address        (state)      rhiwat  shiwat    pid   
tcp4       0      0  127.0.0.1.1111         *.*                    LISTEN       131072  131072   3263 

kill 3263
```

**Comment by pengsongyou** [comment]
Thanks a lot for this trick :) I have included it into the [troubleshooting](https://github.com/pengsongyou/openscene/tree/main/demo#troubleshooting)!
