### ISSUE TITLE
Have met the index error on Nuscene

### ISSUE THREAD

**Issue by superkang12** [pengsongyou/openscene#29]
Have met the following index error on Nuscene

> IndexError: Caught IndexError in DataLoader worker process 0. Original Traceback (most recent call last):   File "/home/kcl/anaconda3/envs/openscene/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop     data = fetcher.fetch(index)   File "/home/kcl/anaconda3/envs/openscene/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch     data = [self.dataset[idx] for idx in possibly_batched_index]   File "/home/kcl/anaconda3/envs/openscene/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>     data = [self.dataset[idx] for idx in possibly_batched_index]   File "/media/kcl/b0beda02-b349-4a4a-b5d0-95769b843737/openscene/dataset/feature_loader.py", line 111, in __getitem__     feat_3d_new[mask] = feat_3d IndexError: The shape of the mask [34752] at index 0 does not match the shape of the indexed tensor [277920, 768] at index 0

**IndexError: The shape of the mask [34752] at index 0 does not match the shape of the indexed tensor [277920, 768] at index 0**

thx.

**Comment by pengsongyou** [comment]
Hi @superkang12,

Thanks for pointing out this error. I found that I the features that I uploaded before were not the correct one, so I uploaded the correct version. Please download via https://cvg-data.inf.ethz.ch/openscene/data/replica_multiview_openseg.zip again.

 Best
Songyou
