### ISSUE TITLE
About ScanNet feature_loader

### ISSUE THREAD

**Issue by HustQBW** [pengsongyou/openscene#3]
Hello,thanks for your great work! I'm sorry that I still have some question about the ScanNet feature_loader.

In ./scripts/feature_fusion/scannet_openseg.py:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/48615375/231582637-2146a01b-d41f-4a9e-a5bd-98496f46d7bc.png">

and in fusion_util.py:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/48615375/231582771-775e50df-f7dc-4f63-9d5c-607f1dbff739.png">

I find that only 2 keys in this pth,which is 'feat' and 'mask_full'

But in feature_loader,your annotation says:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/48615375/231583027-949072ba-e219-4926-8cdb-ba81280e96b1.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/48615375/231583117-86baab9a-59c9-4c6f-81db-e27884ee4b27.png">

Is there any mistake here? What is the key named 'mask'?

Thanks for your answering.

**Comment by pengsongyou** [comment]
Hi @HustQBW, thanks for the great catch! We refactorized our code before the release but forgot to modify this part. The 3-key features are from the legacy processed features (e.g., the only case that I found is the `scannet_multiview_lseg`, if you download it with [the script](https://github.com/pengsongyou/openscene/blob/main/scripts/download_fused_features.sh)). 

I have modified the [`feature_loader.py`](https://github.com/pengsongyou/openscene/blob/main/dataset/feature_loader.py) and modified the description a bit. 

Hope it is clear to you now.

Best
Songyou

**Comment by HustQBW** [comment]
Thanks for your answering! But I'm sorry that I also have one question. If I want to generate my own LSeg multi-view feature now, what I should do is fork the scannet_openseg.py to generate 2-keys feature file. Isn't it? Thanks!

**Comment by pengsongyou** [comment]
@HustQBW yup basically that is the case. However, you need to modify accordingly the feature extractor part [here](https://github.com/pengsongyou/openscene/blob/main/scripts/feature_fusion/fusion_util.py#L42-L68) to adapt for the LSeg.

> Thanks for your answering! But I'm sorry that I also have one question. If I want to generate my own LSeg multi-view feature now, what I should do is fork the scannet_openseg.py to generate 2-keys feature file. Isn't it? Thanks!

**Comment by HustQBW** [comment]
Oh,I see! Thanks! Additionally, I am curious about the pre-trained LSeg model. Which .pth did you use? Thank you!
