### ISSUE TITLE
Question for modification of other per-pixel feature extractor e.g. OV-Seg

### ISSUE THREAD

**Issue by synsin0** [pengsongyou/openscene#31]
I'd like to change the feature extractor to a stronger OV-Seg. However, OV-Seg adopts maskformer head. I am confused with the per-pixel feature used in OpenScene. Is this feature from the backbone (image embedding) or the last two layers in the head? May you provide some instructions on language-aware visual feature extraction from which layer? Thanks.

**Comment by JarveeLee** [comment]
I guess it is the layer whose pixel feature is directly aligned to language space, directly affected by similarity loss.

**Comment by synsin0** [comment]
Got it! Thanks.

**Comment by Wang-pengfei** [comment]
Hi, how do you utilize the results of OV-Seg? I'm also conducting similar experiments, but the results are not very good. I'm not sure where the issue lies.

**Comment by pengsongyou** [comment]
Hi, we actually never did the experiments with OV-Seg, but only LSeg & OpenSeg (check out our paper), so unfortunately I won't be able to provide useful information. But the general rule is to obtain pixel-aligned features and then do the fusion.

The easiest way is to try to modify only [this function](https://github.com/pengsongyou/openscene/blob/main/scripts/feature_fusion/fusion_util.py#L42-L68), and compare the fusion results between OpenSeg features and OV-Seg features.

Best
Songyou

**Comment by Wang-pengfei** [comment]
Thank you very much for your response! I will continue to make further attempts.

**Comment by jy213** [comment]
Hi @Wang-pengfei, I would like to ask if you have successfully changed the 2D feature extractor to OV-Seg? Thank you very much for your attention
