### ISSUE TITLE
How can I play the interactive demo on a remote Ubuntu Server?

### ISSUE THREAD

**Issue by linhaojia13** [pengsongyou/openscene#35]
I’m working on a remote Ubuntu Server via SSH and run `run_demo`. However, it return the error:
```
 freeglut (conf2texture): failed to open display
```
I know that using a local machine with a graphical interface can avoid this problem, but I would like to try runing `run_demo` on a remote server (as it is the only available Linux machine for me). Do you have any experience in this regard?

**Comment by linhaojia13** [comment]
Thank you! Finally, I decide to get a Macbook to play this demo.

**Comment by jedyang97** [comment]
@linhaojia13 , we have had success running it remotely on a linux machine by using VNC.
