### ISSUE TITLE
Something about “nuscenes_openseg.py”

### ISSUE THREAD

**Issue by zhanghao5201** [pengsongyou/openscene#36]
In your code “scripts/feature_fusion/nuscenes_openseg.py”, you simply project all point cloud data at all timestamps in the same scene onto the image data at the last timestamp. I think this is not rigorous. What do you think? I also want to ask, why not directly use the point cloud data at the last timestamp to map and match with the image data?

**Comment by zhanghao5201** [comment]
And maybe you can add the original data "nuscenes/{}", I find the scene name may be different form the data from official website.

**Comment by pengsongyou** [comment]
Hi @zhanghao5201, sorry for the late reply. 

Actually we only process points' features on the last stamp, see [here](https://github.com/pengsongyou/openscene/blob/main/scripts/feature_fusion/nuscenes_openseg.py#L42-L46). However, during our 3D distillation process, we input points from all timestamps, but the supervision is only on the last timestamp. Please check the last paragraph of our Appendix A in our arxiv paper.

Best
Songyou

**Comment by RONINGOD** [comment]
> Hi @zhanghao5201, sorry for the late reply.您好，抱歉回复晚了。
> 
> Actually we only process points' features on the last stamp, see [here](https://github.com/pengsongyou/openscene/blob/main/scripts/feature_fusion/nuscenes_openseg.py#L42-L46). However, during our 3D distillation process, we input points from all timestamps, but the supervision is only on the last timestamp. Please check the last paragraph of our Appendix A in our arxiv paper.实际上我们只处理最后一个印章上的点特征，请参见此处。然而，在我们的 3D 蒸馏过程中，我们输入所有时间戳的点，但监督仅针对最后一个时间戳。请查看我们的 arxiv 论文中附录 A 的最后一段。
> 
> Best Songyou

why don't you input points from all timestamps into LSeg
