### ISSUE TITLE
Creating full 3d map with clip features for a matterport scene

### ISSUE THREAD

**Issue by singhularAdi** [pengsongyou/openscene#37]
Given the precomputed fused features, I am trying to create the full 3d space for a matterport3d scene as a tensor (x, y, z, 768) in order to query the features around a particular point in the scene. Ive tried using the FusedFeatureLoader class to load the features for a scene and put them all together using the coordinates but it does not seem to work well. Is there a better way to do this?

Update: Im unable to find a way to go from the region wise coordinates to a global coordinate system that aligns these different regions together.

**Comment by pengsongyou** [comment]
Hi @singhularAdi 

We actually do the inference not on the entire apartment of Matterport3D, but do them one by one. Say there are 10 rooms in total in an apartment, we run the inference for each one of it. Therefore, we don't really convert to a global coordinate.

Best
Songyou

**Comment by singhularAdi** [comment]
How do you take these rooms and align them for the demo?

**Comment by pengsongyou** [comment]
Luckily it is done already with the gaps, I simply use it :) You can check out how we load them https://github.com/tomfunkhouser/gaps/tree/202489d72a4effa4817684291b1bf6076b6931d2
