### ISSUE TITLE
What do the images need to satisfy?

### ISSUE THREAD

**Issue by yannick-reich** [pengsongyou/openscene#38]
Hi, 
I was wondering what attributes the pictures need? I was starting to look through your code, but maybe there is an easy answer? 
More concretely, I would like to try OpenScene with outdoor scenes made from street view images and point clouds optained through lidar scans. As far as I know, I can only get RGB images from streetview. But at least for the 2D-3D-fusion I probably need intrinsics? 
Thank you for your work on OpenScene and all help would be much appreciated.
Best,
   Yannick

**Comment by pengsongyou** [comment]
Hi Yannick,

Yes, you are right, if you wanna do 2D Fusion, you need to the intrinsic and extrinsic parameters for your RGB images. For indoor scenes with RGB-D images, we utilize the depth to do the visiblity check. For outdoor lidar scenes, there is no depth so we don't do the check. Please check in details the codes under the [`feature_fusion`](https://github.com/pengsongyou/openscene/tree/main/scripts/feature_fusion) folder
