### ISSUE TITLE
training on other 3d datasets(3dfront or s3dis)

### ISSUE THREAD

**Issue by liwell24** [pengsongyou/openscene#39]
Thank you for the great work of open source！

If I want to retrain Openscene on other datasets(3dfront or s3dis),   do I need a corresponding RGBD image in addition to the 3D point cloud?   As far as I know,the answer is yes.  But other datasets don't provide RGBD images of the corresponding scene,  so what should I do in this case.

Looking forward to your reply.
Thank u~

**Comment by pengsongyou** [comment]
Yes, you need the corresponding RGBD images as well to do fusion :) For the case where their is no RGB, you can simply modify the fusion code to basically not do any visibility check. You can check our code [here](https://github.com/pengsongyou/openscene/blob/main/scripts/feature_fusion/fusion_util.py#L132-L134).
