### ISSUE TITLE
How to implement Image-based 3D object detection？can you share your code？

### ISSUE THREAD

**Issue by YuerGu** [pengsongyou/openscene#40]
How to implement Image-based 3D object detection？can you share your code？
do i need to convert images to clip features？

**Comment by pengsongyou** [comment]
Hi @YuerGu 

It is very straightforward. As you said, you need to convert images to the corresponding CLIP features, and then do exactly the same as text-based tasks, i.e. compute the cosine similarity between the CLIP image features with the point features.

Best
Songyou
