### ISSUE TITLE
Question about table 1

### ISSUE THREAD

**Issue by Pixie8888** [pengsongyou/openscene#42]
Hi,

Thanks for releasing code! I have some questions about table 1 in the main paper:
1. Do you use 2D-3D Feature Ensemble to do zero-shot segmentation?
2. How to evaluate zero-shot performance (only test the performance of segmenting new classes)?

**Comment by pengsongyou** [comment]
1. Yes, we use the ensemble feature
2. Yes, since our model was never trained with the GT labels in ScanNet, we simply show the performance on those 4 classes.
