### ISSUE TITLE
error when extracting 2d image features using openseg

### ISSUE THREAD

**Issue by Haerxu** [pengsongyou/openscene#43]
Hi,

I generate multi-view features using scannet_openseg.py, but it gave this error:
![image](https://github.com/pengsongyou/openscene/assets/142866313/92ea9ab8-e962-4980-bec1-b603cedeb774)

The environment is pytorch 1.8 + Cu111. tensorflow 2.13. 
Do you know how to solve it?

**Comment by aminebdj** [comment]
Hey @Haerxu, would you mind sharing how you solved the problem?

**Comment by Haerxu** [comment]
I think it's related to the cuda and tensorflow version. They need to be compatible.

**Comment by aminebdj** [comment]
Hey @Haerxu, It seems to be the case. The problem was solved after I downgraded the tensorflow version to 2.6.0.
