### ISSUE TITLE
Question about the double data augmentations

### ISSUE THREAD

**Issue by yifliu3** [pengsongyou/openscene#44]
Hi, 

I find that the there exists double data augmentations when loading the data. The first time is the rotation and scale augmentation during the voxelizaiton period, and the second time includes several more augmentation strategies. 

May I ask the meaning of the double data augmentation strategy, and why not just perform a single one?

**Comment by yifliu3** [comment]
Besides, I observe that during the evaluation period, the augmentation still exists in the voxelization process. I'm wondering if this is a standard data processing operation.

**Comment by pengsongyou** [comment]
Hi, for data augmentation we actually followed what [BP-Net](https://github.com/wbhu/BPNet) did, and it seems to me a standard strategy.
