### ISSUE TITLE
In Table 1, does the labelsets contain only four categories?

### ISSUE THREAD

**Issue by xiaodongww** [pengsongyou/openscene#48]
Hi, thanks for your work. I have a question about `Table 1`. When evaluating ScanNet, do you set `labelsets` as 20 classes? Or do you set it as 4 classes (`Bookshelf, Desk, Sofa, Toilet`) and all points of the scene will be forced to predict one of the four categories?

**Comment by pengsongyou** [comment]
Good question! If I remember correctly, we actually set the labelsets to 20 classes and simply picked these 4 classes to report.
