### ISSUE TITLE
 Lseg feature extraction

### ISSUE THREAD

**Issue by Wang-pengfei** [pengsongyou/openscene#49]
Hi, do you have plans to open-source the code for Lseg feature extraction? I'm curious about how you determine the crop_size. Additionally, I would like to know if the final extracted feature map is smaller than [240, 320], and if so, is it directly interpolated to [240, 320]?

**Comment by pengsongyou** [comment]
Yes, really sorry, I will work on the code release for this part ASAP.

**Comment by pengsongyou** [comment]
Hi @Wang-pengfei, I am really sorry for not being able to do the code refactorization and cleaning earlier... Sorry for such a long delay...

Please check the repo https://github.com/pengsongyou/lseg_feature_extraction. Let me know if it works for you. I will close the issue for now.

Best
Songyou
