### ISSUE TITLE
How to train 3D per-point encoder

### ISSUE THREAD

**Issue by yjtang249** [pengsongyou/openscene#52]
Hello, 

Thanks for your inspiring work! I still have some questions. In section 3.1 you introduced 2D encoder(per-pixel) OpenSeg/LSeg, which is pretrained on large amounts of data, and stays fixed during inference for any given scene, right? As for 3D encoder(per-point) ε^3D introduced in section 3.2, should we train a new ε^3D from scratch(through distillation) when a new scene is given? If so, how long does it take for a new scene? 
Thank you.

**Comment by pengsongyou** [comment]
You simply pretrain the 3D encoder on a large dataset by distillation. When a new scene is given, you directly apply it to the new input scene's point cloud. It is a generalizable model.
