### ISSUE TITLE
how to eval in the train dataset?

### ISSUE THREAD

**Issue by xuxiaoxxxx** [pengsongyou/openscene#54]
Hi, I want to evaluate on the training set. And I only change the 'split' in our_openseg_pretained.yaml to 'train'. But it dosen't wok, After I've made other minor changes, however the visualisation I ended up with was extremely poor.
![1695295202317](https://github.com/pengsongyou/openscene/assets/55653936/e64114b8-9c54-471a-87e6-922cc81578f1)
Can you help me to slove this problem?

**Comment by xuxiaoxxxx** [comment]
And this is GT.
![1695295287488](https://github.com/pengsongyou/openscene/assets/55653936/0c63c45e-91be-4653-966d-0d280b9efd21)

**Comment by pengsongyou** [comment]
I wonder if you have already solved the problem?

**Comment by xuxiaoxxxx** [comment]
I have sloved this problem. Thanks for your reply!

**Comment by Charlie839242** [comment]
Hi, would you mind shraing how you solved the problem? Thanks a lot!
