### ISSUE TITLE
How to use the code train_mink.sh

### ISSUE THREAD

**Issue by TyroneLi** [pengsongyou/openscene#56]
Hi, I notice there is a code:
https://github.com/pengsongyou/openscene/blob/main/run/train_mink.sh
I wander how to use this part? Thanks

**Comment by pengsongyou** [comment]
Sorry for the late reply. You can simply run:

`sh run/train_mink.sh EXP_DIR CONFIG.yaml`

**Comment by TyroneLi** [comment]
> Sorry for the late reply. You can simply run:
> 
> `sh run/train_mink.sh EXP_DIR CONFIG.yaml`

Hi, I mean what this training script works for? Like, this can further improve the final segmentation performances? Did you use this to train the model?

**Comment by pengsongyou** [comment]
Oh, it is used for training the MinkowskiNet baseline, i.e., train with GT labels. For example, we use this to obtain the number of MinkowskiNet in Table 2.
