### ISSUE TITLE
How to extract LSeg feature

### ISSUE THREAD

**Issue by Outlying3720** [pengsongyou/openscene#57]
Hello, thanks for your appreciative work. But I met some difficulty in extracting LSeg feature. 

The feature I extracted will lead to a low training result. Which is similar to other issues.

So, it's glad if you could provide LSeg extraction code. Thank you very much!

**Comment by pengsongyou** [comment]
Hi @Outlying3720 Thanks for reaching out. I finally got time to start working on cleaning the multi-view fusion code for LSeg. I promise that I will release this part early next week (our ETH server is down until this weekend so I need some time to test on Monday).

Thanks for being patient!

**Comment by pengsongyou** [comment]
Hi @Outlying3720, I managed to get it done earlier :) 

Please check the repo https://github.com/pengsongyou/lseg_feature_extraction. Let me know if it works for you. I will close the issue for now.

Best
Songyou

**Comment by Outlying3720** [comment]
Wow! Thank you very much for such a prompt reply!
I will try it immediately.
