### ISSUE TITLE
Confusion about sinput of model

### ISSUE THREAD

**Issue by HalvesChen** [pengsongyou/openscene#58]
Hi, I have some problems about the 'sinput' of model. It seems to use '[1,1,1]' as sparsetensor on [https://github.com/pengsongyou/openscene/blob/0f369bc73d0724ae24b5e46bbada193f8ee9d193/dataset/point_loader.py#L169](url). Do I misunderstand?

**Comment by pengsongyou** [comment]
We by default in [config](https://github.com/pengsongyou/openscene/blob/main/config/scannet/ours_openseg.yaml#L8) consider no point color is used as input, so we set [1, 1, 1] as the point color for all points.
