### ISSUE TITLE
Misalignment in unprojected RGBD images

### ISSUE THREAD

**Issue by ayushjain1144** [pengsongyou/openscene#60]
Hi @pengsongyou ,

Thank you for your excellent work, and especially in preprocessing the data into a common format!

I am using your 2D pre-processed matterport data and I am unprojecting it to 3D using the provided intrinsics and extrinsics.  It gave me the following pointcloud, which does not look good I think: 
<img width="1072" alt="Screenshot 2023-11-02 at 2 33 10 AM" src="https://github.com/pengsongyou/openscene/assets/28894174/1935fde0-eb92-4de6-a2e3-fca1e1880e49">
wandb link: https://wandb.ai/ayushjain1144/m3d/runs/kdbjp0xg?workspace=user-ayushjain1144

I did some further analysis and found that all images unprotected from same camera id are well aligned, but there seems to be some translation misalignment when combining images from different cameras. For eg: in this [wandb link](https://wandb.ai/ayushjain1144/m3d/runs/u7x3s0cf?workspace=user-ayushjain1144), `unprojected` is the pointcloud from same camera uiud, `unprojected_all` is combined pointcloud from all these cameras. 

I am fairly certain that my unprojection code is ok, because it works well on scannet. Do you have any ideas on what might be wrong? Do the visualizations look ok on your side?

Thank you!

**Comment by pengsongyou** [comment]
Hi @ayushjain1144 thanks for your interest in our work! I am not sure how exactly you do your unprojection from 2D to 3D, but there might be some differences between ScanNet and Matterport3D camera poses. I am not sure what the problem is, but can you try one thing:
```python
pose[:3, 1] *= -1.0
pose[:3, 2] *= -1.0
```
Maybe this might make a difference. If not, maybe you should check if there are some differences in Matterport3D and ScanNet poses.

Best
Songyou

**Comment by ayushjain1144** [comment]
Hi, 

thank you for your reply. I am not using raw matterport data but your processed data where I think you already did that processing over the poses. I also tried doing this processing again over your data, which just makes it into the original poses, and the misalignment is still there. 

My unprojection code is pretty standard I think and has worked for several other datasets too. does unprotected pointclouds on your side looked ok?


```
def unproject(intrinsics, poses, depths, mask_valid=True):
    """
    Inputs:
        intrinsics: B X V X 3 X 3
        poses: B X V X 4 X 4 (torch.tensor)
        depths: B X V X H X W (torch.tensor)
    
    Outputs:
        world_coords: B X V X H X W X 3 (all valid 3D points)
        valid: B X V X H X W (bool to indicate valid points)
                can be used to index into RGB images
                to get N X 3 valid RGB values
    """
    B, V, H, W = depths.shape
    fx, fy, px, py = intrinsics[..., 0, 0][..., None], intrinsics[..., 1, 1][..., None], intrinsics[..., 0, 2][..., None], intrinsics[..., 1, 2][..., None]

    y = torch.arange(0, H).to(depths.device)
    x = torch.arange(0, W).to(depths.device)
    y, x = torch.meshgrid(y, x)

    x = x[None, None].repeat(B, V, 1, 1).flatten(2)
    y = y[None, None].repeat(B, V, 1, 1).flatten(2)
    z = depths.flatten(2)
    x = (x - px) * z / fx
    y = (y - py) * z / fy
    cam_coords = torch.stack([
        x, y, z, torch.ones_like(x)
    ], -1)

    world_coords = (poses @ cam_coords.permute(0, 1, 3, 2)).permute(0, 1, 3, 2)
    world_coords = world_coords[..., :3] / world_coords[..., 3][..., None]

    world_coords = world_coords.reshape(B, V, H, W, 3)

    if mask_valid:
        world_coords[depths == 0] = -10
    return world_coords
```

**Comment by pengsongyou** [comment]
I wonder if you got to try to apply the sign on the translation as I
suggested in the last message? I just wanna see if there is something wrong
with my provided poses.

**Comment by ayushjain1144** [comment]
I did try it and it makes things worse very weirdly:

<img width="1045" alt="Screenshot 2023-11-03 at 2 37 21 AM" src="https://github.com/pengsongyou/openscene/assets/28894174/3ae2dcfc-1195-4abe-b573-6f66fdcfec9b">

To be precise, this is what I did:

```
poses = torch.from_numpy(np.array(poses)).float().cuda()
poses[..., :3, 1] *= -1.0
poses[..., :3, 2] *= -1.0
```

earlier the images were aligned per camera uiud, but multiplying with -1 breaks that too. here is also a wandb link to visualizations: https://wandb.ai/ayushjain1144/m3d/runs/nvq21cwp?workspace=user-ayushjain1144

Thank you Songyou for your reply and continued help!

**Comment by pengsongyou** [comment]
> I did try it and it makes things worse very weirdly:
> 
> <img alt="Screenshot 2023-11-03 at 2 37 21 AM" width="1045" src="https://user-images.githubusercontent.com/28894174/280200271-3ae2dcfc-1195-4abe-b573-6f66fdcfec9b.png">
> To be precise, this is what I did:
> 
> ```
> poses = torch.from_numpy(np.array(poses)).float().cuda()
> poses[..., :3, 1] *= -1.0
> poses[..., :3, 2] *= -1.0
> ```
> 
> earlier the images were aligned per camera uiud, but multiplying with -1 breaks that too. here is also a wandb link to visualizations: https://wandb.ai/ayushjain1144/m3d/runs/nvq21cwp?workspace=user-ayushjain1144
> 
> Thank you Songyou for your reply and continued help!

That's quite strange... Can you first try to run our [feature fusion code](https://github.com/pengsongyou/openscene/blob/main/scripts/feature_fusion/matterport_openseg.py), see whether it is correct. We project from 3D to 2D to obtain the per-point features. If it works, maybe you can check if you can adapt your unprojection from 2D to 3D accordingly?

Best
Songyou
