### ISSUE TITLE
Question about 3D point cloud visualization

### ISSUE THREAD

**Issue by WeitaiKang** [pengsongyou/openscene#64]
I am a novice researcher in the 3D field and would like to inquire about your code for visualizing 3D point clouds. Could you please open source the code for 3D point cloud visualization? Specifically, I am referring to the visualization image like ScanNet in 

*openscene/media/benchmark_screenshot.jpg*

**Comment by pengsongyou** [comment]
It is already open sourced. Please check https://github.com/pengsongyou/openscene/blob/main/run/evaluate.py#L349-L350
