### ISSUE TITLE
Create a multi-view fusion feature using median method

### ISSUE THREAD

**Issue by wooca12** [pengsongyou/openscene#65]
Hello. 
Thanks for your great job!

I read a part of ablation on multi-view fusion strategy in your paper.

 I want to know implement details about multi-view fusion using  median method, specifically.
 
Could you give simple code or explain details about multi-view fusion using median?

**Comment by pengsongyou** [comment]
Thanks for your interest!

Below you can find how we calculate the median feature for each 3D point. Assume we have a set of features for a point called `feat_total`, where it is of the size of feature_dim x number_of_features_for_this_point.

```python
feat_median = feat_total.float().median(dim=-1)[0]
distance = (feat_total - feat_median[:, None]).norm(dim=0)
feat = feat_total[:, distance.argmin()]
```
`feat` corresponds to the median feature.

Hope it makes sense.
