### ISSUE TITLE
Question about the labeling of scannet 2d data

### ISSUE THREAD

**Issue by Nyohohoho** [pengsongyou/openscene#66]
Thank you for your work.
I would like to use the same data as you did for my research, and I need the labels in scannet 2d data.
I read your code, and figured out that you are mapping the labels to 1-40 which is NYU40.
But you are using 20 classes of scannet for 3D evaluation, right?
When I downloaded your preprocessed data and checked the data range of label files, it is 0-255.
How am I supposed to get the 1-40 labeling or 0-19 labeling as the 3D counterpart?

Thanks!

**Comment by pengsongyou** [comment]
Really sorry for the delayed reply, I did not check the issue. The label range is not 0-255, but 0 to 19 for 20 classes, and 255 means there is no annotation for the corresponding points. For the label mapping, we simply followed the previous work like BP-Nets.
