### ISSUE TITLE
NaN or Inf found in input tensor

### ISSUE THREAD

**Issue by jy213** [pengsongyou/openscene#75]
When executing the distill.sh script, I consistently encounter the error message "NaN or Inf found in input tensor", accompanied by 'NaN' values in the loss calculations. Has anyone also encountered this issue before?
![屏幕截图 2024-04-22 121337](https://github.com/pengsongyou/openscene/assets/109406942/aa5831e7-b85a-4520-b8ff-c55efe19e347)

**Comment by jingmengzhoumomenta** [comment]
hi，may I ask how did u fix this problem? I meet the same in ScanNet.TKS!

**Comment by solarChenxi** [comment]
I have encountered the same problem , it seem to do with the ensemble features, some of them are empty
