### ISSUE TITLE
LSeg Feature and Evaluate

### ISSUE THREAD

**Issue by HustQBW** [pengsongyou/openscene#8]
Hello, @pengsongyou ! Thanks for your great job! I implement my own LSeg feature and evaluate. But unfortunately, it has a big gap with using your multiview-lseg-feature for evaluation. 

So I am curious about your implement of LSeg feature extraction. Have you ever used some tricks like multi-scale evaluation? How did you solve the problem that the (320,240) 'image_dim' (240 cannot be divided by 32.). (I just resize to (320,256) and after forward, I interpolate back to (320,240)

Thansk for your reply!

**Comment by HustQBW** [comment]
Can you share your lseg feature code, if convenient? My email is 995020860@qq.com. Thanks!

**Comment by pengsongyou** [comment]
Hi @HustQBW , as shown in the [TODO](https://github.com/pengsongyou/openscene#todo), the LSeg feature fusion is still under refactorization and cleaning. I will release as soon as it is ready. Stay tuned.
